In [ ]:
#Importando as libs necessárias para a implementação do algoritmo Classificador de Distância Mínima
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
# Carregando a base de dados Iris
iris = load_iris()
X = iris.data
y = iris.target

# Primeiras amostras e classes
print("Características das primeiras 5 amostras:\n", X[:5])
print("Classes das primeiras 5 amostras:", y[:5])


Características das primeiras 5 amostras:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Classes das primeiras 5 amostras: [0 0 0 0 0]


In [ ]:
# Dividindo o conjunto de dados em treino e teste (70% treino, 30% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Exibir as formas dos conjuntos de dados para verificação
print(f"Forma do conjunto de treino: {X_train.shape}")
print(f"Forma do conjunto de teste: {X_test.shape}")


Forma do conjunto de treino: (105, 4)
Forma do conjunto de teste: (45, 4)


In [ ]:
# Calculando os vetores protótipos (médias) para cada classe (comprimento e largura das sépalas, comprimento e largura das pétalas)
prototypes = []
for label in np.unique(y_train):
    prototypes.append(X_train[y_train == label].mean(axis=0))
prototypes = np.array(prototypes)

# Exibindo os protótipos calculados
print("Vetores protótipos (médias) para cada classe:\n", prototypes)


Vetores protótipos (médias) para cada classe:
 [[4.96451613 3.37741935 1.46451613 0.2483871 ]
 [5.86216216 2.72432432 4.21081081 1.3027027 ]
 [6.55945946 2.98648649 5.54594595 2.00540541]]


In [ ]:
def minimum_distance_classifier(X, prototypes):
    predictions = []
    for sample in X:
        # Calculando distância euclidiana até cada protótipo
        distances = np.linalg.norm(prototypes - sample, axis=1)
        # Atribuinddo a classe do protótipo mais próximo
        predictions.append(np.argmin(distances))
    return np.array(predictions)

# Prevendo as classes para o conjunto de testes
y_pred = minimum_distance_classifier(X_test, prototypes)


In [ ]:
# Calculando a acurácia
print(f'Acurácia do classificador de distância mínima: {accuracy:.2f}')


Acurácia do classificador de distância mínima: 0.96


In [ ]:
# Comparando algumas previsões com as classes reais
comparacao = pd.DataFrame({'Real': y_test, 'Previsto': y_pred})
print(comparacao.head(10))


   Real  Previsto
0     1         1
1     0         0
2     2         2
3     1         1
4     1         2
5     0         0
6     1         1
7     2         2
8     1         1
9     1         1
